### ISSUE TITLE
最新版点击‘关于’报错

### ISSUE THREAD

**Issue by hhrensheng** [zsh2401/AutumnBox#40]
最新测试版
系统 win11最新版 
点击 关于 报错

**Comment by hhrensheng** [comment]
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Loading: PrintInformations()
[2022-01-27 15:45:09][GeneralAppLoader/Info]:======================
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Installed as E:\Win11_WSA\AutumnBox-Canary
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Run as Administrator
[2022-01-27 15:45:09][GeneralAppLoader/Info]:AutumnBox version: 2021.2.22.0
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Core library version: 11.9.0.0
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Windows version: 10.0.22000.0
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Clr version: 5.0.3
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Commit: 
[2022-01-27 15:45:09][GeneralAppLoader/Info]:======================
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Loading: InitHandyControl()
[2022-01-27 15:45:09][GeneralAppLoader/Info]:Loading: InitAutumnBoxBasic()
[2022-01-27 15:45:09][GeneralAppLoader/Info]:killing other adb processes
[2022-01-27 15:45:11][GeneralAppLoader/Info]:autumnbox-adb-server is starting
[2022-01-27 15:45:13][Win32AdbManager/Info]:statring adb server 1:* daemon not running; starting now at tcp:25763
[2022-01-27 15:45:13][Win32AdbManager/Info]:statring adb server 2:* daemon started successfully
[2022-01-27 15:45:13][Win32AdbManager/Info]:statring adb server 3:
[2022-01-27 15:45:13][Win32AdbManager/Info]:statring adb server 4:
[2022-01-27 15:45:13][GeneralAppLoader/Info]:autumnbox-adb-server is started at 127.0.0.1:25763
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: InitAutumnBoxOpenFx()
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:Initializing Open Framework 11.9.0.0
[2022-01-27 15:45:13][OpenFx/Info]:Registering componnets
[2022-01-27 15:45:13][OpenFx/Info]:Base components are registered
[2022-01-27 15:45:13][OpenFx/Info]:Management components are registered
[2022-01-27 15:45:13][OpenFx/Info]:Open API components are registered
[2022-01-27 15:45:13][DreamLibManager/Info]:Found file: AutumnBox.Extensions.Essentials.dll
[2022-01-27 15:45:13][DreamLibManager/Info]:Found file: AutumnBox.Extensions.Standard.dll
[2022-01-27 15:45:13][DreamLibManager/Debug]:There are 2 extension file
[2022-01-27 15:45:13][DreamLibManager/Debug]:There are 2 assemblies
[2022-01-27 15:45:13][DreamLibManager/Info]:There are 2 librarians
[2022-01-27 15:45:13][DreamLibManager/Info]:autumnbox-essentials
[2022-01-27 15:45:13][DreamLibManager/Info]:AutumnBox Core Modules
[2022-01-27 15:45:13][DreamLibManager/Info]:Calling ready method: autumnbox-essentials
[2022-01-27 15:45:13][EssentialsLibrarin/Info]:librarian autumnbox-essentials 's ready
[2022-01-27 15:45:13][EssentialsLibrarin/Info]:EssentialsLibrarin's ready
[2022-01-27 15:45:13][ClassComponentsLoader/Info]:Found 0 class component
[2022-01-27 15:45:13][DreamLibManager/Info]:Calling ready method: AutumnBox Core Modules
[2022-01-27 15:45:13][CoreLib/Info]:librarian AutumnBox Core Modules 's ready
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:Open framework api system is initialized
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:There are 2 librarian(s) and 41 registered extension(s).
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ECmdLauncher has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ELeafUIDemo has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EPSLauncher has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ETest has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAutumnBoxAdFetcher has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAutumnBoxExtensionStore has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAutumnBoxGuideViewer has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAutumnBoxRestarter has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAutumnBoxUpdateChecker has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EDeviceRebooter has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EDonateCardRegister has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EEnableCurrentDeviceNetDebugging has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ENetDeviceConnecter has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ENetDeviceDisconnecter has been registerd by autumnbox-essentials
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ESwitchABSlot has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EPermissionDogActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EApkInstaller has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EScreenShoter has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EBreventActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EClearAccounts has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EClearUsers has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EDpiModifier has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EGCM has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EGreenifyGranter has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EShizukuActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EStopAppMaxWellActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EUnlockSystemParation has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAirForzenActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EAnzenboksuActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EBlackHole has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EFreezeYou has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EHideAnzen has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EIceBox has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EIslandActivator has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EStopApp has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:ETaiChi has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EDeviceOwnerRemover has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EFilePusher has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EFlashBoot has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EFlashRecovery has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][OpenFxManagerImpl/Info]:EOemLock has been registerd by AutumnBox Core Modules
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: InitErrorHandlerSystem()
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: InitializeLanguageSystem()
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: InitUtilities()
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: RunDeviceListener()
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: AddLeafCards()
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Loading: DisplayGuide()
[2022-01-27 15:45:13][GeneralAppLoader/Info]:Done!
[2022-01-27 15:45:13][EAutumnBoxAdFetcher/Warn]:System.Net.WebException: An error occurred while sending the request.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at AutumnBox.Essentials.Extensions.EAutumnBoxAdFetcher.DisplayTextAd(IXCardsManager xCardsManager)
[2022-01-27 15:45:32][VMDeviceDash/Warn]:error
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:34][VMDeviceDash/Warn]:error
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:35][VMDeviceDash/Warn]:error
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:36][VMDeviceDash/Warn]:error
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:37][VMDeviceDash/Warn]:error
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:37][FatalHandler/Warn]:AutumnBox Exception 01/27/2022    15:45:37

Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Windows.Markup.XamlParseException: 对类型“AutumnBox.GUI.ViewModels.VMAbout”的构造函数执行符合指定的绑定约束的调用时引发了异常。
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at AutumnBox.GUI.ViewModels.VMAbout..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at AutumnBox.GUI.Views.Windows.AboutWindow.InitializeComponent()
   at AutumnBox.GUI.Views.Windows.AboutWindow..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at AutumnBox.GUI.Services.Impl.WindowManager.CreateWindow(String windowName, Object[] args)
   at AutumnBox.GUI.Services.Impl.WindowManager.ShowDialog(String windowName)
   at AutumnBox.GUI.MVVM.ViewModelBase._ShowWindowDialog(Object para)
   at AutumnBox.GUI.MVVM.MVVMCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Message:
Exception has been thrown by the target of an invocation.

Source:
System.Private.CoreLib

Inner:
System.Windows.Markup.XamlParseException: 对类型“AutumnBox.GUI.ViewModels.VMAbout”的构造函数执行符合指定的绑定约束的调用时引发了异常。
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at AutumnBox.GUI.ViewModels.VMAbout..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at AutumnBox.GUI.Views.Windows.AboutWindow.InitializeComponent()
   at AutumnBox.GUI.Views.Windows.AboutWindow..ctor()

[2022-01-27 15:45:39][VMDeviceDash/Warn]:error
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:39][EssentialsLibrarin/Info]:librarian autumnbox-essentials's destorying
[2022-01-27 15:45:39][CoreLib/Info]:librarian AutumnBox Core Modules's destorying
[2022-01-27 15:45:39][LocalAdbServerKiller/Info]:
[2022-01-27 15:45:39][LocalAdbServerKiller/Info]:
[2022-01-27 15:45:40][LocalAdbServerKiller/Info]:成功: 已终止进程 "adb.exe"，其 PID 为 23424。
[2022-01-27 15:45:40][LocalAdbServerKiller/Info]:
[2022-01-27 15:45:40][LocalAdbServerKiller/Warn]:
[2022-01-27 15:45:40][VMDeviceDash/Warn]:error
AutumnBox.Basic.Exceptions.CommandErrorException: 


   at AutumnBox.Basic.Calling.CommandResultExtension.ThrowIfError(CommandResult result)
   at AutumnBox.Basic.Device.ManagementV2.OS.StatGetter.GetTotal()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshCpu()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:42][VMDeviceDash/Warn]:error
AutumnBox.Basic.Exceptions.CommandErrorException: * daemon not running; starting now at tcp:25763
* daemon started successfully
adb.exe: device '127.0.0.1:58526' not found



   at AutumnBox.Basic.Calling.CommandResultExtension.ThrowIfError(CommandResult result)
   at AutumnBox.Basic.Device.ManagementV2.OS.MemInfoGetter.Get()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.RefreshRam()
   at AutumnBox.GUI.ViewModels.VMDeviceDash.Refresh()
[2022-01-27 15:45:43][LocalAdbServerKiller/Info]:The command taskkil has successfully executed.
[2022-01-27 15:45:43][Win32AdbManager/Info]:Adb Server has been stopped.
